config/routes.rb
DocuMentorV5::Application.routes.draw do

  resources :clients

  resources :slide_images

  resources :questions

  resources :assignments

  resources :filled_sections

  resources :docuchecks

  resources :case_studies

  resources :concepts

  resources :products

  get "welcome/index"

  match 'documents'=>"documents#index"
  match 'administrator' => 'welcome#admin_view'

  match 'user' => 'welcome#user_view'
  match 'author' => 'welcome#author_view'

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  devise_for :users

  match 'product_dashboard' => 'products#dashboard'
  match 'concept_dashboard' => 'concepts#dashboard'

  match ":docket_id/documents"=>"documents#view_documents",:as=>"view_documents"
  match ':docket_id/documents/:document_id/pages' => "documents#view_document_pages",:as=>"view_document_pages"
  match ':docket_id/documents/:document_id/page/:page_id/customize' => 'documents#document_customize_view',:as=>"document_customize_view"
  match '/documents/structure_form/:page_id/:count' => "documents#structure_form"
  match '/docupedia' => "welcome#doclauncher"

  match 'add_new_slide' => 'slide_managements#add_new_slide'
  match 'slide' => 'slide_managements#index'
  match 'save_slide' => 'slide_managements#save_slide'
  match 'view_slide' => 'slide_managements#view_slides'

  match 'show_reference_doc/:docket_id/:document_id/:page_number'=>'test_management#show_reference_document',:as=>"show_reference_doc"

  match 'test_landing_page' => "test_management#landing_page"
  match 'play_quiz' => "test_management#play_quiz"
  match 'save_quiz_data' => "test_management#save_quiz_data"
  match '/test_manamgement/list_documents/:assignment_id/:docket_id' => "test_management#list_documents",:as=>"list_documents"
  match '/test_management/play_document_test/:docucheck_id/:sequence_number' => "test_management#play_document_test",:as=>"play_document_test"
  match 'save_document_results' => "test_management#save_document_results"
  match 'take_tutorials' => "test_management#take_tutorials"
  match "/test_management/practice/:case_study_id"=>"test_management#start_practice",:as=>"start_practice"
  match '/test_management/list_dockets/:assignment_id'=>"test_management#list_dockets",:as=>"list_dockets"

  match 'result_landing_page'=>'result_management#landing_page'
  match '/result_management/show_docket_list/:case_study_id/:assignment_id'=>'result_management#show_docket_list',:as=>"show_docket_list"
  match '/result_management/show_document_list/:case_study_id/:assignment_id/:docket_id'=>'result_management#show_document_list',:as=>"show_document_list"
  match '/result_management/show_corrected_page/:assignment_id/:docket_id/:docucheck_id/:page_id'=>'result_management#show_corrected_page',:as=>"show_corrected_page"

  match 'practice_landing_page'=>'practice_management#landing_page'
  match 'list_practice_details/:case_study_id'=>'practice_management#list_practice_details',:as=>"list_practice_details"
  match 'practice_document'=>'practice_management#practice_document'
  match 'save_practice_document_results'=>'practice_management#save_practice_document_results'

  root :to => 'welcome#index'

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  skip_before_filter :authenticate_user!  , :only => [:index]

  def index
  end

  def user_view
  end

  def doclauncher
    if params[:id]
      @document=Document.find(params[:id])
    end
  end

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/admin_view.html.erb
<%= content_for :page_header do %>
    <span style="border: none;font-size: 40px;font-weight: bold;vertical-align: middle;text-align: left;width: 130px;color: white">DocuMentor</span>

<% end %>
<div class="row">
  <div class="span10">
    <h1>My DashBoard</h1>

    <div class="row">
      <div class="span6">



Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi. Nam liber tempor cum soluta nobis eleifend option congue nihil imperdiet doming id quod mazim placerat facer possim assum. Typi non habent claritatem insitam; est usus legentis in iis qui facit eorum claritatem. Investigationes demonstraverunt lectores legere me lius quod ii legunt saepius. Claritas est etiam processus dynamicus, qui sequitur mutationem consuetudium lectorum. Mirum est notare quam littera gothica, quam nunc putamus parum claram, anteposuerit litterarum formas humanitatis per seacula quarta decima et quinta decima. Eodem modo typi, qui nunc nobis videntur parum clari, fiant sollemnes in futurum.
        <br/>

      </div>
      <div class="span3">
        <br/>
        <% if !current_user %>
            <div style="text-align: right;color: #556b2f;font-size: 20px;font-weight: bold;margin-right: 20px;">
              <a href="#" data-controls-modal="sign_up_form" data-backdrop="static" class="btn primary">Sign Up...</a>
            </div>
        <% else %>
            <div style="text-align: right;color: #556b2f;font-size: 20px;font-weight: bold;margin-right: 20px;">
              <%= link_to "Enter >>", "#", :class=>"btn primary" %>
            </div>
        <% end %>
        <div id="sign_up_form" class="modal hide fade">
          <div class="modal-header">
            <a href="#" class="close"> &times; </a>

            <h3>Sign Up</h3>
          </div>

          <%= form_for(resource, :as => resource_name, :url => registration_path(resource_name)) do |f| %>

              <div class="modal-body">

                <div class="clearfix">
                  <%= f.label :email %>
                  <div class="input">  <%= f.email_field :email %></div>

                  <%= f.label :password %>
                  <div class="input">  <%= f.password_field :password %></div>

                  <%= f.label :re_enter %>
                  <div class="input">  <%= f.password_field :password_confirmation %></div>
                </div>

              </div>


              <div class="modal-footer">

                <div>
                  <%= f.submit "Sign up", :class=>"btn error" %>
                </div>
              </div>
          <% end %>
        </div>

      </div>
    </div>
  </div>

  <div class="span4">
    <table>
      <tr style="border: none;">
        <td style="border: none;">
          <%= image_tag("docket.jpeg", :size => "64x64") %>
        </td>
        <td style="border: none;">
         <%= link_to "Manage Components",component_integrated_view_path,:class=>"primary btn span5" %>
        </td>
      </tr>
      <tr>
        <td>
          <%= image_tag("documents.jpeg", :size => "64x64") %>
        </td>
        <td>
        <%= link_to  "Manage your Documents",document_integrated_view_path,:class => "primary btn span5" %>
        </td>
      </tr>
      <tr>
        <td>
          <%= image_tag("test.jpeg", :size => "70x70") %>
        </td>
        <td>
        <%= link_to "Manage Tests" ,test_integrated_view_path,:class => "primary btn span5"%>
        </td>
      </tr>
      <tr>
        <td>
          <%= image_tag("user.jpeg", :size => "70x70") %>
        </td>
        <td>
         <%= link_to "Manage Users",user_management_path,:class=>"primary btn span5" %>
        </td>
      </tr>

      <tr>
        <td>
          <%= image_tag("dept.jpeg", :size => "70x70") %>
        </td>
        <td>
         <%= link_to "Manage Departments",new_department_path,:class=>"primary btn span5" %>
        </td>
      </tr>

    </table>
  </div>
</div>

<!-- /container -->

app/views/welcome/author_view.html.erb
<%= content_for :page_header do %>
    <span style="border: none;font-size: 40px;font-weight: bold;vertical-align: middle;text-align: left;width: 130px;color: white">DocuMentor</span>



<% end %>

<style type="text/css">
  /*.span6{*/
      /*height: 200px;*/
  /*}*/

</style>
<div class="row">
  <div class="span6">
    <%= link_to image_tag('document.jpeg',:size => "200x200"), documents_path, :class => " span5",:title => "Manage Documents" %>
  </div>
  <div class="span6">
    <%= link_to image_tag('concept.jpeg',:size => "200x200"), concepts_path, :class => "span5",:title => "Manage Concepts" %>
  </div>
</div>

<div class="row">
  <div class="span6">
    <%= link_to image_tag('case-study.jpeg',:size => "200x200"), case_studies_path, :class => "span5",:title => "Manage Your Case Studies" %>
  </div>
  <div class="span6">
    <%= link_to image_tag('assignment.jpeg',:size => "200x200"), assignments_path, :class => " span5",:title => "Manage Assignments" %>
  </div>
</div>

app/views/welcome/doclauncher.html.erb
<%= stylesheet_link_tag "exclusions/anythingslider" %>
<%= javascript_include_tag "exclusions/jquery.anythingslider.min" %>
<%= javascript_include_tag "exclusions/jquery.anythingslider.fx.min" %>

<script type="text/javascript">
$(function () {
  $(".chzn-select").chosen().change(function () {
  });
  $('#docgal').anythingSlider({
    vertical:true
  });
});

function goTo() {
  var sE = null, url;
  if (document.getElementById) {
    sE = document.getElementById('urlList');
  } else if (document.all) {
    sE = document.all['urlList'];
  }
  if (sE && (url = sE.options[sE.selectedIndex].value)) {
    location.href = url;
  }
}
</script>

<style>
#slide {
  width: 640px;
  height: 500px;

}
li{
  padding:5px;
  border-radius:5px;
  line-height:15px;
  margin-bottom:0;
  list-style-type:none;
  background: rgb(169,3,41); /* Old browsers */
  background: -moz-linear-gradient(-45deg,  rgb(169,3,41) 0%, rgb(143,2,34) 44%, rgb(109,0,25) 100%); /* FF3.6+ */
  background: -webkit-gradient(linear, left top, right bottom, color-stop(0%,rgb(169,3,41)), color-stop(44%,rgb(143,2,34)), color-stop(100%,rgb(109,0,25))); /* Chrome,Safari4+ */
  background: -webkit-linear-gradient(-45deg,  rgb(169,3,41) 0%,rgb(143,2,34) 44%,rgb(109,0,25) 100%); /* Chrome10+,Safari5.1+ */
  background: -o-linear-gradient(-45deg,  rgb(169,3,41) 0%,rgb(143,2,34) 44%,rgb(109,0,25) 100%); /* Opera 11.10+ */
  background: -ms-linear-gradient(-45deg,  rgb(169,3,41) 0%,rgb(143,2,34) 44%,rgb(109,0,25) 100%); /* IE10+ */
  background: linear-gradient(-45deg,  rgb(169,3,41) 0%,rgb(143,2,34) 44%,rgb(109,0,25) 100%); /* W3C */
  filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#a90329', endColorstr='#6d0019',GradientType=1 ); /* IE6-9 fallback on horizontal gradient */

}

a:hover{
  color:orange;
  font-weight:bolder;
  text-decoration:none;
  font-size:18px;
}

</style>


<div style="margin-top: 10px;width:960px;margin:auto; padding-bottom:50px;">

  <div class="row-fluid">
    <div class="span6">
      <a href="#" class="btn btn-inverse" style="overflow:hidden;margin-top:50px;margin-left: 25px;height:250px;width:420px;border-radius: 20px;">
        <img src="/assets/family-papers-400.jpg" style="margin-left: 200px;margin-top:-10px;height:270px;width:270px">

        <div style="margin-top: -200px;margin-left: -120px;;color:#ffffff; font-size: 48px;">DocuPedia</div>
        <div style="margin-top: 30px;margin-left: 10px;width:180px;color:white; font-size: 18px;">
          Look through the database of documents to understand the whats and whys of documentation...
        </div>
      </a>
      <br>
      <br>
      <br>
      <h1 style="text-align:center">Choose a Document</h1>

    </div>
    <br>
    <div class="span5" style="height:360px;overflow:auto">
      <br/>
      <br/>
      <ul>
        <% Document.all.each do |doc| %>
        <li><%= link_to doc.name.titleize, "/assets/samples/DocuPres1/SanctionLetter.html" %></li>
        <% end %>
      </ul>
    </div>
  </div>

</div>

app/views/welcome/documentor_view.html.erb
<%= content_for :head do %>
    <style type="text/css">
        .content {
            /*background: transparent;*/
        }
    </style>
<% end %>

<%= content_for :page_header do %>

<% end %>
    <div class="row" style="height: 250px">
      <div class="span6 offset2">
        <table class="table">
          <tr>
            <td style="text-align: center">
              <%= image_tag("docket.png", :size => "150x150") %>
              <br>
              <%= link_to "Dockets", docket_integrated_view_path, :class => "btn-warning btn span3 btn-large", :style => "text-align:centre" %>
            </td>
            <td style="text-align: center">
              <%= image_tag("documents.png", :size => "150x150") %>
              <br>
              <%= link_to "Documents", document_sets_integrated_view_path, :class => "btn-warning btn span3 btn-large" %>
            </td>
            </tr>
            <tr>
            <td style="text-align: center">
              <%= image_tag("department.png", :size => "150x150") %>
              <br>
              <%= link_to "Departments", department_management_path, :class => "btn-warning btn span3 btn-large" %>
            </td>
            <td style="text-align: center">
              <%= image_tag("tests.png", :size => "150x150") %>
              <br>
              <%= link_to "Tests", test_integrated_view_path, :class => "btn-warning btn span3 btn-large" %>
            </td>
          </tr>
        </table>
      </div>
    </div>
<div class="row">
</div>

<!-- /container -->

app/views/welcome/index.html.erb
<%= content_for :head do %>
<style>
.hero-unit {
	background: rgb(196, 3, 23); /* Old browsers */
	background: -moz-linear-gradient(-45deg, rgb(196, 3, 23) 0%, rgb(107, 2, 9) 44%, rgb(99, 0, 1) 100%); /* FF3.6+ */
	background: -webkit-gradient(linear, left top, right bottom, color-stop(0%, rgb(196, 3, 23)), color-stop(44%, rgb(107, 2, 9)), color-stop(100%, rgb(99, 0, 1))); /* Chrome,Safari4+ */
	background: -webkit-linear-gradient(-45deg, rgb(196, 3, 23) 0%, rgb(107, 2, 9) 44%, rgb(99, 0, 1) 100%); /* Chrome10+,Safari5.1+ */
	background: -o-linear-gradient(-45deg, rgb(196, 3, 23) 0%, rgb(107, 2, 9) 44%, rgb(99, 0, 1) 100%); /* Opera 11.10+ */
	background: -ms-linear-gradient(-45deg, rgb(196, 3, 23) 0%, rgb(107, 2, 9) 44%, rgb(99, 0, 1) 100%); /* IE10+ */
	background: linear-gradient(-45deg, rgb(196, 3, 23) 0%, rgb(107, 2, 9) 44%, rgb(99, 0, 1) 100%); /* W3C */
	filter: progid:DXImageTransform.Microsoft.gradient(startColorstr = '#c40317', endColorstr = '#630001', GradientType = 1); /* IE6-9 fallback on horizontal gradient */

}
</style>
<% end %>
<div>
	<br/>

	<div id="sign_up_form" class="modal hide fade">
		<div class="modal-header">
			<a class="close" data-dismiss="modal"> &times; </a>

			<h3>Sign Up</h3>
		</div>
		<%= form_for(resource, :as => resource_name, :url => registration_path(resource_name)) do |f| %>
		<div class="modal-body">
			<div class="clearfix">
				<%= f.label :email %>
				<div class="input">  <%= f.email_field :email %></div>
				<%= f.label :password %>
				<div class="input">  <%= f.password_field :password %></div>
				<%= f.label :re_enter %>
				<div class="input">  <%= f.password_field :password_confirmation %></div>
			</div>
		</div>
		<div class="modal-footer">
			<div>
				<%= f.submit "Sign up", :class => "btn btn-warning btn-large" %>
			</div>
		</div>
		<% end %>
	</div>

</div>

<div class="row-fluid">
	<div class="span4">
		<%= image_tag "logo.png", :class => "span4" %>
	</div>
	<div class="span7" style="margin-top:20px;">
		<div class="hero-unit">
			<div class="row-fluid">
				<div class="span12">
					<h1 style="color:white;">The Documentation Trainer</h1>
					<br/>
					<br/>

					<div class="pull-right">
						<% if !current_user %>
						<div style="font-size: 20px;font-weight: bold;">
							<a href="#sign_up_form" data-toggle="modal" data-backdrop="static" class="btn btn-warning btn-large">
								Sign Up
							</a>
							<%= link_to "Know More", "#", :class => "btn btn-info btn-large" %>
						</div>
						<% else %>
						<div style="color: #556b2f;font-size: 20px;font-weight: bold;">
							<%= link_to "Enter", "#", :class => "btn btn-warning btn-large" %>
							<%= link_to "Know More", "#", :class => "btn btn-info btn-large" %>
						</div>
						<% end %>
					</div>
				</div>
			</div>
		</div>
	</div>

</div>

<!-- /container -->

app/views/welcome/ptemplar.html.erb
<%= content_for :head do %>
    <style type="text/css">
        .content {
            background: transparent;
        }
    </style>
<% end %>

<!-- First set the slide size -->

<% @slide_height = 550 %>
<% @slide_width = 940 %>

<!------------------------------------------------------------------------------------->

<!-- Title Slide -->

<!--Put in the title text-->


<%# @titletext = "How Many roads must a man work down?" %>

<!--Call the renderer-->

<%#= render_cell :title_slide,
                :panelled, # Can be no_anim or panelled
                :slide_height => @slide_height, # The slide height
                :slide_width => @slide_width, # The slide height
                :title => @titletext, # Can be blank
                :positionx => '100', # X-Position of Title
                :positiony => '100', # Y-Position of Title
                :location => 'left', # Can be left, right, top or bottom. Position x & y are used.
                :width => '300', # Width of Title
                :font_size => '18', # Font-size of the text
                :text_color => 'white', # Color of the text
                :panel_color => 'lightblue', # Color of the panel
                :panel_image => '/assets/fantasy.jpg', # Image on the panel
                :text_shadow => 'gray', # Color of the text shadow
                #:back_gradient_1=>'#0099ff',           # 'From'color when using CSS gradient for the slide background
                #:back_gradient_2=>'#003399',           # 'To'color when using CSS gradient for the slide background
                :back_image => '/assets/fantasy.jpg',     # Background Image, lower priority than gradient
    #:back_color=>'white'                   # Background color, lower priority than background image
%>

<!------------------------------------------------------------------------------------->

<!-- Only a Bullet List-->


<!--First define the bullet list-->

<% @bullets = Array.new
   @bullets[0]= "Short Term Loans are a good source of money"
   @bullets[1]= "They carry an interest rate"
   @bullets[2]= "You have to pay them back after their tenor"
   @bullets[3]= "You need to give collateral to take the loan"
   @bullets[4]= "You need to give collateral to take the loan"
%>

<%= render_cell :bullet_list,
                :no_anim,                                       # Can be :no_anim
                :slide_height=>@slide_height,                   # The slide height
                :slide_width=>@slide_width,                     # The slide width
                :title=>'Any Title',                            # Can be blank
                :banner_img=>'/assets/short-term-loans.png',   # The Photo
                :list_items=>@bullets,                          # The Array of Bullets
                :font_size=>'18',                               # Font-size of the bullet text
                :text_color=>'white',                           # Color of the bullet text
                :bullet_img=>'/assets/bullet-1.png',            # Image to use for bullet
                :back_gradient_1=>'#0099ff',                    # 'From'color when using CSS gradient for the slide background
                :back_gradient_2=>'#003399',                    # 'To'color when using CSS gradient for the slide background
                :back_image=>'/assets/ljk.jpg',                 # Background Image, lower priority than gradient
                :back_color=>'white'                            # Background color, lower priority than background image
%>


<!------------------------------------------------------------------------------------->

<!--One Photo and a Bullet List-->


<!--First define the bullet list-->

<%# @bullets = Array.new
   @bullets[0]= "Short Term Loans are a good source of money"
   @bullets[1]= "They carry an interest rate"
   @bullets[2]= "You have to pay them back after their tenor"
   @bullets[3]= "You need to give collateral to take the loan"
   @bullets[4]= "You need to give collateral to take the loan"
%>

<!--Then call the renderer-->

<%#= render_cell :photo_and_bullet_list,
                :sliding_anim,                                       # Can be :no_anim,:no_anim_flipped, :sliding_anim, :sliding_anim_flipped
                :slide_height=>@slide_height,                   # The slide height
                :slide_width=>@slide_width,                     # The slide width
                :title=>'Any Title',                            # Can be blank
                :banner_img=>'/assets/short-term-loans.png',   # The Photo
                :list_items=>@bullets,                          # The Array of Bullets
                :font_size=>'18',                               # Font-size of the bullet text
                :text_color=>'white',                           # Color of the bullet text
                :bullet_img=>'/assets/bullet-1.png',            # Image to use for bullet
                :back_gradient_1=>'#0099ff',                    # 'From'color when using CSS gradient for the slide background
                :back_gradient_2=>'#003399',                    # 'To'color when using CSS gradient for the slide background
                :back_image=>'/assets/ljk.jpg',                 # Background Image, lower priority than gradient
                :back_color=>'white'                            # Background color, lower priority than background image
%>

<!------------------------------------------------------------------------------------->

<!-- Flash Cards -->

<!-- First define the flash cards in the array -->

<%# @flipimages = Array.new
   @flipimages[0]=["debt2.jpeg", "#", "A secured loan is a loan in which the borrower pledges some asset (e.g. a car or property) as collateral."]
   @flipimages[1]=["debt.jpeg", "#", "Unsecured loans are monetary loans that are not secured against the borrower's assets."]
   @flipimages[2]=["debt3.jpeg", "#", "Demand loans are short term loans (typically no more than 180 days) that are atypical in that they do not have fixed dates for repayment and carry a floating interest rate which varies according to the prime rate."]
   @flipimages[3]=["ptotem.jpeg", "#", "Know More"]

   @slide_text="A loan is a type of debt. Like all debt instruments, a loan entails the redistribution of financial assets over time, between the lender and the borrower.<br/><br/>

In a loan, the borrower initially receives or borrows an amount of money, called the principal, from the lender, and is obligated to pay back or repay an equal amount of money to the lender at a later time. Typically, the money is paid back in regular installments, or partial repayments; in an annuity, each installment is the same amount.<br/><br/>

The loan is generally provided at a cost, referred to as interest on the debt, which provides an incentive for the lender to engage in the loan. In a legal loan, each of these obligations and restrictions is enforced by contract, which can also place the borrower under additional restrictions known as loan covenants. "
%>

<!--Then call the renderer-->

<%#= render_cell :flash_cards,
                :with_text,                             # Can be :full_slide or :with_text or :with_bullets
                :slide_height=>@slide_height,           # The slide height
                :slide_width=>@slide_width,             # The slide width
                :title=>'Definition',                   # Can be blank
                :slide_text=>@slide_text,               # The Slide Text to add
                :text_width=>'280',                     # The Slide Text width
                :list_items=>@bullets,                  # The Array of Bullets
                :bullet_img=>'/assets/bullet-1.png',    # Image to use for bullet
                :font_size=>'14',                       # Font-size of the text
                :text_color=>'black',                   # Color of the text
                :table_height=>'550',                   # The Height of the Table of flash cards
                :table_width=>'550',                    # The Width of the Table of flash cards
                :cols=>'2',                             # No. of columns in the Table of flash cards
                :rows=>'2',                             # No. of rows in the Table of flash cards
                :flip_images=>@flipimages,              # The Array of Flash Cards
                :flip_style=>'vertical',                # Can be 'vertical' or 'horizontal'
                #:back_gradient_1=>'#0099ff',            # 'From'color when using CSS gradient for the slide background
                #:back_gradient_2=>'#003399',            # 'To'color when using CSS gradient for the slide background
                #:back_image=>'/assets/ljk.jpg',         # Background Image, lower priority than gradient
                :back_color=>'white'                    # Background color, lower priority than background image
%>

<!------------------------------------------------------------------------------------->

<!-- Process Maps -->

<!-- First enter Process Points like this -->
<!-- @process_blocks[x]=[ Serial#, Picture, Link, Text, Left, Top, Height, Width, Color, TextColor]-->

<%# @process_blocks = Array.new
   @process_blocks[0]=["1", "incg_hover2.gif", "http://www.ptotem.com", "Start Here", "50", "200", "150", "150", "transparent", "white"]
   @process_blocks[1]=["2", "incg_hover2.gif", "http://www.ptotem.com", "Submit Documents", "300", "200", "150", "150", "transparent", "white"]
   @process_blocks[2]=["3", "incg_hover2.gif", "http://www.ptotem.com", "Get Approvals", "550", "200", "150", "150", "transparent", "white"]
%>

<!-- Then enter the Connection like this -->
<!-- @connections[x]=[ StartBlock, SBLocation, EndBlock, EBLocation, Color, Type]-->

<%# @connections = Array.new
   @connections[0]=["1", "RightMiddle", "2", "LeftMiddle", "green", "Straight"]
   @connections[1]=["2", "RightMiddle", "3", "LeftMiddle", "green", "Straight"]
   @connections[2]=["3", "TopCenter", "1", "TopCenter", "red", "Bezier"]
   #@connections[3]=["3", "BottomCenter", "2", "BottomCenter", "red", "Bezier"]
%>

<!--Then call the renderer-->

<%#= render_cell :map,
                :basic,                                 # Can be :full_slide or :with_text or :with_bullets
                :slide_height=>@slide_height,           # The slide height
                :slide_width=>@slide_width,             # The slide width
                :title=>'Process Map',                  # Can be blank
                :process_points=>@process_blocks,       # The various process points
                :connections=>@connections,             # The connections between the processes
                :font_size=>'14',                       # Font-size of the text
                :text_color=>'black',                   # Color of the text
                #:back_gradient_1=>'#0099ff',            # 'From'color when using CSS gradient for the slide background
                #:back_gradient_2=>'#003399',            # 'To'color when using CSS gradient for the slide background
                #:back_image=>'/assets/ljk.jpg',         # Background Image, lower priority than gradient
                :back_color=>'white'                    # Background color, lower priority than background image
%>