config/routes.rb
DocuMentorV5::Application.routes.draw do

  resources :clients

  resources :slide_images

  resources :questions

  resources :assignments

  resources :filled_sections

  resources :docuchecks

  resources :case_studies

  resources :concepts

  resources :products

  get "welcome/index"

  match 'documents'=>"documents#index"
  match 'administrator' => 'welcome#admin_view'

  match 'user' => 'welcome#user_view'
  match 'author' => 'welcome#author_view'

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  devise_for :users

  match 'product_dashboard' => 'products#dashboard'
  match 'concept_dashboard' => 'concepts#dashboard'

  match ":docket_id/documents"=>"documents#view_documents",:as=>"view_documents"
  match ':docket_id/documents/:document_id/pages' => "documents#view_document_pages",:as=>"view_document_pages"
  match ':docket_id/documents/:document_id/page/:page_id/customize' => 'documents#document_customize_view',:as=>"document_customize_view"
  match '/documents/structure_form/:page_id/:count' => "documents#structure_form"
  match '/docupedia' => "welcome#doclauncher"

  match 'add_new_slide' => 'slide_managements#add_new_slide'
  match 'slide' => 'slide_managements#index'
  match 'save_slide' => 'slide_managements#save_slide'
  match 'view_slide' => 'slide_managements#view_slides'

  match 'show_reference_doc/:docket_id/:document_id/:page_number'=>'test_management#show_reference_document',:as=>"show_reference_doc"

  match 'test_landing_page' => "test_management#landing_page"
  match 'play_quiz' => "test_management#play_quiz"
  match 'save_quiz_data' => "test_management#save_quiz_data"
  match '/test_manamgement/list_documents/:assignment_id/:docket_id' => "test_management#list_documents",:as=>"list_documents"
  match '/test_management/play_document_test/:docucheck_id/:sequence_number' => "test_management#play_document_test",:as=>"play_document_test"
  match 'save_document_results' => "test_management#save_document_results"
  match 'take_tutorials' => "test_management#take_tutorials"
  match "/test_management/practice/:case_study_id"=>"test_management#start_practice",:as=>"start_practice"
  match '/test_management/list_dockets/:assignment_id'=>"test_management#list_dockets",:as=>"list_dockets"

  match 'result_landing_page'=>'result_management#landing_page'
  match '/result_management/show_docket_list/:case_study_id/:assignment_id'=>'result_management#show_docket_list',:as=>"show_docket_list"
  match '/result_management/show_document_list/:case_study_id/:assignment_id/:docket_id'=>'result_management#show_document_list',:as=>"show_document_list"
  match '/result_management/show_corrected_page/:assignment_id/:docket_id/:docucheck_id/:page_id'=>'result_management#show_corrected_page',:as=>"show_corrected_page"

  match 'practice_landing_page'=>'practice_management#landing_page'
  match 'list_practice_details/:case_study_id'=>'practice_management#list_practice_details',:as=>"list_practice_details"
  match 'practice_document'=>'practice_management#practice_document'
  match 'save_practice_document_results'=>'practice_management#save_practice_document_results'

  root :to => 'welcome#index'

end

app/models/document.rb
class Document < ActiveRecord::Base

  has_and_belongs_to_many :case_studies
  #has_and_belongs_to_many :concepts
  has_many :pages, :dependent => :destroy ,:order => :sequence_number
  has_many :docuchecks, :dependent => :destroy

  has_many :filled_sections,:dependent => :destroy
  has_many :dockets_documents,:dependent => :destroy
  has_many :dockets,:through => :dockets_documents



end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  def index
    @dockets=Docket.all
  end

  def view_documents
    @docket=Docket.find(params[:docket_id])
    @documents=@docket.documents
  end

  def view_document_pages
    @docket=Docket.find(params[:docket_id])
    @document=Document.find(params[:document_id])
    @pages=@document.pages
  end

  def document_customize_view

    @docket=Docket.find(params[:docket_id])
    @document=Document.find(params[:document_id])

    @page=Page.find(params[:page_id])
    @component_types=ComponentType.all
    @blank_sections = @page.blank_sections
    @blank_section=BlankSection.new


  end

  def structure_form


    @blank_section_count=params[:count].to_i

    @page = Page.find(params[:page_id].to_i)
    @existing_blank_sections = @page.blank_sections
    @existing_blank_sections.each do |section|
      section.destroy
    end

    @blank_section_count.times do |i|

      @blank_section = BlankSection.new
      @blank_section.page_id=@page.id
      @component=Component.find_by_name(params[:fields][i][:comp_name])
      @blank_section.component_id=@component.id
      @blank_section.xpos=params[:fields][i][:xpos].to_i
      @blank_section.ypos=params[:fields][i][:ypos].to_i
      @blank_section.height=params[:fields][i][:height].to_i
      @blank_section.width=params[:fields][i][:width].to_i
      @blank_section.save

    end

    render :text => "Ok", :notice => 'Blank Section #{i} was successfully created.'
  end
end

app/helpers/document_helper.rb
module DocumentHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/documents/document_customize_view.html.erb
<%= content_for :head do %>

    <script type="text/javascript">

        function show_spec(link) {
            //alert(link.text());
            // $(".type_"+$('#component_field').attr("value")).show();
            //  $("#selection"+selection_no).find("div").css("visibility", "visible");
            //alert( link.parent().parent().attr("class"));

            if (link.parent().next().next().css("visibility") == "visible")
                link.parent().next().next().css("visibility", "hidden");

            else
            {
                link.parent().next().next().find("div.type #example").multiselect();
                link.parent().next().next().css("visibility", "visible");

                
            }
            
        }




        $(function () {

            var spec = new Array();
            var s="";
            <% @component_types.each do |component_type| %>
            <% component_type.component_specs.each do |s_specs| %>
            s=s+'<%= check_box_tag s_specs.name ,s_specs.name,false,:class=>"spec_check_box"%> <%= s_specs.name %> <br>';
            <% end %>

            //var s = <%#= select_tag :component_type_spec,options_from_collection_for_select(component_type.component_specs,"name","name"),:id=>"example",:multiple=>true -%>;
            spec[<%= component_type.id %>] = '<div id="type_<%= component_type.id %>" class="c_type" style="visibility: hidden;background:grey;text-align:left" >' + s + '</div>';
            s="";
            <% end %>


            $(document).on("change",".spec_check_box",function(){

                var prev_title=$(this).parent().prev().prev().attr("title");
                if ($(this).prop("checked"))
                {

                var new_title=prev_title+" - "+$(this).attr("value");

                }
                else
                {
                    var new_title=prev_title.replace(" - "+$(this).attr("value"),"");

                }
                $(this).parent().prev().prev().attr("title",new_title);
                $(this).parent().prev().text(new_title);

            })  ;

            var component_name = "";
            $('#component_field').attr("value", "empty");

            // Select a Component
            $('.component_icon').click(function () {

                $('.component_icon').removeClass('selected_icon');
                $('.component_icon a').removeClass('error').addClass('primary');
                $(this).addClass('selected_icon');
                $(this).children('a').removeClass('primary').addClass('error');
                $('#component_field').attr("value", $(this).attr('id'));
                component_name = $(this).attr("title");
            });


            $('.selectiondiv').draggable();
            $('.selectiondiv').resizable();

            var selection_no = 0;

            $("#DocumentFrame").click(function (e) {

//                if (e.target.hasClass('xbutton')) {
//                    $(".xbutton").trigger('click');
//                }
//                alert($('#component_field').attr("value"));
//
                if ($('#component_field').attr("value") != "empty") {
                    var LEFT = e.pageX
                    var TOP = e.pageY
                    var this_selection = "#selection" + selection_no;

                    $('#DocumentFrame').after('<div id="selection' + selection_no + '" class="selectiondiv ui-widget-content">  </div>');

                    $(this_selection).append(" <div class='ui-widget-header' title='" +component_name + "' style='margin: 3px;color:black; font-size:<%= @page.line_height %>px'>" + component_name + "<a href='#' onclick='$(this).parent().parent().remove();' class='pull-right' style='font-size: 12px;color:black;margin-right: 3px;'>x</a>" + "<a href='#' onclick='show_spec($(this))' class='pull-right' style='font-size: 12px;color:black;margin-right: 3px;'>+</a>" + "</div> "+"<div class='white_box_text'>"+component_name+" </div>"+ spec[parseInt($('#component_field').attr("value"))]);

                    // Use CSS to place your selection div
                    $("#selection" + selection_no).css({
                        position:'absolute',
                        zIndex:5000,
                        left:LEFT,
                        top:TOP,
                        width:100,
                        height:40
                    });

                    $(".c_type").css({
                        position:'relative',
                        zIndex:5000,
                        left:100,
                        top:0 ,
                    width:150

                    });

                    $(this_selection).show();
                    $(this_selection).draggable();
                    $(this_selection).resizable();
                    selection_no += 1;
                } else {
                    alert("Please pick a component type first!");
                }

            });

            $('#save_button').click(function () {
                var data = {fields:[]};
                var count = $('.selectiondiv').length;

                $('.selectiondiv').each(function () {
                    data["fields"].push({
                        comp_name:$(this).find('div.ui-widget-header').attr("title"),
                        width:$(this).width(),
                        height:$(this).height(),
                        xpos:$(this).position().left,
                        ypos:$(this).position().top})
                });
                $.ajax({
                    url:'/documents/structure_form/<%= @page.id %>/' + count,
                    type:"post",
                    data:JSON.stringify(data),
                    contentType:"application/json",
                    success:function (data) {

                    }
                });
            });

        });


    </script>
    <style type="text/css">
        .content {
            background: transparent;
        }

        .page-header {
            background: transparent;
            position: fixed;
            left: 25px;
            border: none;
            height: 600px;
            width: 220px;
            overflow: auto;
        }

        .docuframe {
            width: 900px;
            height: 1080px;
            margin: 0px auto;
            padding: 0px;
            background-image: url("<%= @page.blank_form.url(:medium) %>");
            background-repeat: no-repeat;
            margin-left: 220px
        }

        .component_icon {
            cursor: pointer;
        }

        .selected_icon {
            margin-left: 30px;
        }

        .selectiondiv {
            position: absolute;
            zIndex: 5000;
            border: 1px solid black
        }
    </style>

<% end %>



<div class="page-header" style="position:fixed; color:white;font-weight: bold;margin-top: 20px">
  <%= link_to image_tag('save.png', :size => '40x40'), "#", :class => "btn-success btn", :id => 'save_button' %>
  <br/>
  <br/>

  <% @component_types.each do |component_type| %>
      <div id="<%= component_type.id %>" title="<%= component_type.name %>" class="component_icon" style="margin-bottom: 5px;">

        <%= link_to component_type.name, "#", :class => 'span2 btn-primary btn' %>
        <br>
        <br>
      </div>
  <% end %>


  <br/>
  <%= link_to "Back",view_document_pages_path(@docket.id,@document.id),:class=>"btn-warning btn" %>
</div>

<div class="row" style="text-align: center; background: transparent">
  <div id="DocumentFrame" class="docuframe">
  </div>

  <% @blank_sections.each do |blank_section| %>
      <div id="<%= blank_section.id %>"
           class="selectiondiv"
           style=
                   "       position:absolute;
                           z-index:5000;
                           top:<%= blank_section.ypos %>px;
                           left:<%= blank_section.xpos %>px;
                           width:<%= blank_section.width %>px;
                           height:<%= blank_section.height %>px;
                   ">

        <div class='ui-widget-header' title='<%= Component.find(blank_section.component_id).name %>' style='margin: 3px;'>
          <%= ComponentType.find_by_name(blank_section.component.name.split(" - ").first).name %>


          <a href='#' onclick='$(this).parent().parent().remove();' class='pull-right' style='font-size: 12px;color:white;margin-right: 3px;'>x</a>
          <a href='#' onclick='show_spec($(this))' class='pull-right' style='font-size: 12px;color:black;margin-right: 3px;'>+</a>

        </div>
        <div class='white_box_text'> <%= blank_section.component.name %></div>
        <% component_parts=blank_section.component.name.split(" - ") %>
        <% @component_type=ComponentType.find_by_name(blank_section.component.name.split(" - ").first) %>
        <div id="type_<%= @component_type.id %>" class="c_type" style="visibility:hidden;background:grey;text-align:left" >
          <%@component_type.component_specs.each do |s_specs| %>
             <% if component_parts.include?(s_specs.name)%>
                  <% status=true %>
                  <% else %>

                  <% status=false %>
                  <% end %>
             <%= check_box_tag s_specs.name ,0,status,:class=>"spec_check_box"%> <%= s_specs.name %> <br>
          <% end %>

        </div>
      </div>

  <% end %>
  <%= hidden_field_tag :component_id, "", :id => "component_field" %>

</div>

app/views/documents/index.html.erb
<h2>Listing all the Dockets</h2>


<table class="table table-striped table-bordered table-condensed">

  <th>Docket Name</th>
  <th>Link</th>
  <% @dockets.each do |docket| %>
      <tr>
  <td><%= docket.name %></td>
  <td><%= link_to "View Documents",view_documents_path(docket.id) %></td>
      </tr>

  <% end %>
  <tr>
    <td>   <%= link_to "Back",author_path,:class=>"btn btn-warning" %></td>
  </tr>


</table>

app/views/documents/view_document_pages.html.erb
<h2>Listing all the documents</h2>


<table class="table table-striped table-bordered table-condensed">

  <th>Document Name</th>
  <th>Link</th>
  <% @pages.each do |page| %>
      <tr>
        <td><%= page.name %></td>
        <td><%= link_to "Customize",document_customize_view_path(:page_id=>page.id) %></td>
      </tr>

  <% end %>
  <tr>
 <td>   <%= link_to "Back",view_documents_path(@docket.id),:class=>"btn btn-warning" %></td>
  </tr>

</table>

app/views/documents/view_documents.html.erb
<h2>Listing all the documents</h2>


<table class="table table-striped table-bordered table-condensed">

  <th>Docket Name</th>
  <th>Link</th>
  <% @documents.each do |document| %>
      <tr>
        <td><%= document.name %></td>
        <td><%= link_to "View pages",view_document_pages_path(:document_id=>document.id) %></td>
      </tr>

  <% end %>
  <tr>
    <td>   <%= link_to "Back",documents_path,:class=>"btn btn-warning" %></td>
  </tr>

</table>