config/routes.rb
DocuMentorV5::Application.routes.draw do

  resources :clients

  resources :slide_images

  resources :questions

  resources :assignments

  resources :filled_sections

  resources :docuchecks

  resources :case_studies

  resources :concepts

  resources :products

  get "welcome/index"

  match 'documents'=>"documents#index"
  match 'administrator' => 'welcome#admin_view'

  match 'user' => 'welcome#user_view'
  match 'author' => 'welcome#author_view'

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  devise_for :users

  match 'product_dashboard' => 'products#dashboard'
  match 'concept_dashboard' => 'concepts#dashboard'

  match ":docket_id/documents"=>"documents#view_documents",:as=>"view_documents"
  match ':docket_id/documents/:document_id/pages' => "documents#view_document_pages",:as=>"view_document_pages"
  match ':docket_id/documents/:document_id/page/:page_id/customize' => 'documents#document_customize_view',:as=>"document_customize_view"
  match '/documents/structure_form/:page_id/:count' => "documents#structure_form"
  match '/docupedia' => "welcome#doclauncher"

  match 'add_new_slide' => 'slide_managements#add_new_slide'
  match 'slide' => 'slide_managements#index'
  match 'save_slide' => 'slide_managements#save_slide'
  match 'view_slide' => 'slide_managements#view_slides'

  match 'show_reference_doc/:docket_id/:document_id/:page_number'=>'test_management#show_reference_document',:as=>"show_reference_doc"

  match 'test_landing_page' => "test_management#landing_page"
  match 'play_quiz' => "test_management#play_quiz"
  match 'save_quiz_data' => "test_management#save_quiz_data"
  match '/test_manamgement/list_documents/:assignment_id/:docket_id' => "test_management#list_documents",:as=>"list_documents"
  match '/test_management/play_document_test/:docucheck_id/:sequence_number' => "test_management#play_document_test",:as=>"play_document_test"
  match 'save_document_results' => "test_management#save_document_results"
  match 'take_tutorials' => "test_management#take_tutorials"
  match "/test_management/practice/:case_study_id"=>"test_management#start_practice",:as=>"start_practice"
  match '/test_management/list_dockets/:assignment_id'=>"test_management#list_dockets",:as=>"list_dockets"

  match 'result_landing_page'=>'result_management#landing_page'
  match '/result_management/show_docket_list/:case_study_id/:assignment_id'=>'result_management#show_docket_list',:as=>"show_docket_list"
  match '/result_management/show_document_list/:case_study_id/:assignment_id/:docket_id'=>'result_management#show_document_list',:as=>"show_document_list"
  match '/result_management/show_corrected_page/:assignment_id/:docket_id/:docucheck_id/:page_id'=>'result_management#show_corrected_page',:as=>"show_corrected_page"

  match 'practice_landing_page'=>'practice_management#landing_page'
  match 'list_practice_details/:case_study_id'=>'practice_management#list_practice_details',:as=>"list_practice_details"
  match 'practice_document'=>'practice_management#practice_document'
  match 'save_practice_document_results'=>'practice_management#save_practice_document_results'

  root :to => 'welcome#index'

end

app/models/concept.rb
class Concept < ActiveRecord::Base
  has_and_belongs_to_many :products
  #has_and_belongs_to_many :documents
  has_many :slides, :dependent => :destroy
  has_many :questions, :dependent => :destroy
  has_many :slides,:dependent => :destroy

end

app/controllers/concepts_controller.rb
class ConceptsController < ApplicationController

  def index
    @concepts = Concept.all
    @concept = Concept.new

  end

  def show

    @concept = Concept.find(params[:id])

  end

  def new
    @concept = Concept.new

  end

  def create
    @concept = Concept.new(params[:concept])
    if @concept.save
      if !params[:integrated_view].nil?
        redirect_to concept_dashboard_path, :notice => "Successfully created concept."
      else
        redirect_to concepts_url, :notice => "Successfully created concept."
      end
    else
      render :new
    end
  end

  def edit
    @concept = Concept.find(params[:id])
    if !params[:get].nil?
      render :layout => false
    end
  end

  def update
    @concept = Concept.find(params[:id])
    if @concept.update_attributes(params[:concept])
      if !params[:integrated_view].nil?
        redirect_to concept_dashboard_path, :notice => "Successfully created concept."
      else
        redirect_to concepts_url, :notice => "Successfully created concept."
      end


    else
      render :edit
    end
  end

  def destroy
    @concept = Concept.find(params[:id])
    @concept.destroy
    if !params[:integrated_view].nil?

      redirect_to concept_dashboard_path, :notice => "Successfully destroyed concept."
    else
      redirect_to concepts_url, :notice => "Successfully destroyed concept."
    end
  end

  def parse_save_from_excel
    test_file = params[:excel_file]
    file = FileUploader.new
    if file.store!(test_file)
      book = Spreadsheet.open "#{file.store_path}"
      sheet1 = book.worksheet 0

      @concept = []
      @errors = Hash.new
      @counter = 0

      sheet1.each 1 do |row|
        @counter+=1
        p = Concept.new

        p.name = row[0]
        unless Concept.find_by_name(p.name)
          if p.valid?
            p.save
          else
            @errors["#{@counter+1}"] = p.errors
          end
        end
      end
      file.remove!
      if @errors.empty?
        redirect_to concept, notice: 'All Dummy data were successfully uploaded.'
      else
        redirect_to concept, notice: 'There were some errors in your upload'
      end

    else
      redirect_to concept, notice: 'Dummy datum could not be successfully uploaded.'
    end
  end

  def dashboard
    @concepts = Concept.all
    @concept = Concept.new

  end
end

app/helpers/concepts_helper.rb
module ConceptsHelper
end

app/views/concepts/_form.html.erb
<%= semantic_form_for @concept do |f| %>
  <%= f.inputs do %>
    <%= f.input :name %>
  <% end %>

  <%= f.butto.ns do %>
    <%= f.commit_button :button_html => {:class=>"btn btn-info btn-large", :style=>"padding:10px;font-weight:bolder"} %>
  <% end %>
<% end %>

app/views/concepts/dashboard.html.erb
<%= content_for :head do %>
    <%= stylesheet_link_tag "exclusions/jquery_data_table" %>
    <%= javascript_include_tag "exclusions/jquery.dataTables.min" %>


    <script type="text/javascript">
        $(function () {
            $('#searcher').dataTable({
                "bJQueryUI":true,
                "sPaginationType":"full_numbers"
            });

            $('form').submit(function () {
                $('form').append("<input type='hidden' name='integrated_view' value='yes'> ");
                return true;
            });
        })
    </script>
<% end %>

<%= content_for :page_header do %>
    <div class="pull-left" style="border: none;margin-left: 130px;margin-top: 60px;font-size: 48px;color:white;">
      Concepts
    </div>
<% end %>

<div class="row-fluid">

  <div class="span2" style="text-align: center;margin-top: 30px;">
    <br/>
    <a href="#new_form" data-toggle="modal" data-backdrop="static" class="btn btn-info span2">
      <h2 style="color:white;">Add New</h2>
    </a>

    <div id="new_form" class="modal hide fade">
      <div class="modal-header">
        <a class="close" data-dismiss="modal"> &times; </a>

        <h3>Create new concept</h3>
      </div>
      <div class="modal-body">
        <%= render 'form' %>
      </div>
    </div>

    <a href="#upload_form" data-toggle="modal" data-backdrop="static" class="btn btn-info span2">
      <h2 style="color:white;">Upload</h2>
    </a>

    <div id="upload_form" class="modal hide fade">
      <div class="modal-header">
        <a class="close" data-dismiss="modal"> &times; </a>

        <h3>Upload Excel File</h3>
      </div>
      <%= form_tag('/concept/parse_save_from_excel', :multipart => true) do |f| %>
          <div class="modal-body">
            Select an Excel File :
            <%= file_field_tag :excel_file %>
          </div>

          <div class="modal-footer">
            <%= submit_tag 'Submit', :class => "large btn primary pull-left" %>
          </div>
      <% end -%>
    </div>

    <a href=" <%= new_concept_path %>" class="add_new btn btn-info span2">
      <h2 style="color:white;">Download</h2>
    </a>

  </div>

  <div class="span9">
    <table class="display pull-left span9" cellpadding="0" cellspacing="0" border="0" id="searcher">
      <thead>
      <tr>
        <th style="text-align: left;">Name</th>
        <th style="text-align: right;">Manage</th>
      </tr>
      </thead>
      <tbody>
      <% @concepts.each do |concept| %>
          <tr>
            <td style="vertical-align: middle;">
              <a href="#show_details" data-toggle="modal" data-backdrop="static" style="font-size: 20px;"><%= concept.name %></a>
            </td>


            <td class="options pull-right">
              <a href="#edit_form" data-toggle="modal" class="btn-warning btn">Edit</a>
              <%= link_to "Destroy", concept, :confirm => 'Are you sure?', :method => :delete, :class => "btn-danger btn" %>
              <%= link_to "Add Documents", "add_documents/#{concept.id}", :class => "btn-warning btn" %>

            </td>

            <div id="edit_form" class="modal hide fade">
              <div class="modal-header">
                <a data-dismiss="modal" class="close"> &times; </a>

                <h3>Edit a record</h3>
              </div>
              <div class="modal-body">
                <%= render 'form'%>
              </div>
            </div>

          </tr>


          <div id="show_details" class="modal hide fade">
            <div class="modal-header">
              <a class="close" data-dismiss="modal"> &times; </a>

              <h3>Concept</h3>
            </div>
            <div class="modal-body">
              <p>
                <strong>Name:</strong>
                <%= concept.name %>
              </p>
              <p>
                <strong>Description:</strong>
                <%= concept.description %>
              </p>

            </div>

            <div class="modal-footer">
              <a class="close" data-dismiss="modal"> Back </a>
            </div>
          </div>
      <%- end -%>
      </tbody>
    </table>

  </div>

</div>
<br/>

app/views/concepts/edit.html.erb
<h1>Editing concept</h1>

<%= render 'form' %>

<%= link_to 'Show', @concept %> |
<%= link_to 'Back', concepts_path %>

app/views/concepts/index.html.erb
<h1>Listing concepts</h1>

<table class="table table-striped table-bordered table-condensed">
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th></th>
    <th></th>
  </tr>

<% @concepts.each do |concept| %>
  <tr>
    <td><%= concept.name %></td>
    <td><%= concept.description %></td>

    <td><%= link_to "Add Slide" ,slide_path(:concept_id=>concept.id)%></td>
    <td><%= link_to "View Slides" ,view_slide_path(:concept_id=>concept.id)%></td>
  </tr>
<% end %>
</table>

<br />

app/views/concepts/new.html.erb
<h1>New concept</h1>

<%= render 'form' %>

<%= link_to 'Back', concepts_path %>

app/views/concepts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @concept.name %>
</p>

<p>
  <b>Description:</b>
  <%= @concept.description %>
</p>


<%= link_to 'Edit', edit_concept_path(@concept) %> |
<%= link_to 'Back', concepts_path %>