config/routes.rb
DocuMentorV5::Application.routes.draw do

  resources :clients

  resources :slide_images

  resources :questions

  resources :assignments

  resources :filled_sections

  resources :docuchecks

  resources :case_studies

  resources :concepts

  resources :products

  get "welcome/index"

  match 'documents'=>"documents#index"
  match 'administrator' => 'welcome#admin_view'

  match 'user' => 'welcome#user_view'
  match 'author' => 'welcome#author_view'

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  devise_for :users

  match 'product_dashboard' => 'products#dashboard'
  match 'concept_dashboard' => 'concepts#dashboard'

  match ":docket_id/documents"=>"documents#view_documents",:as=>"view_documents"
  match ':docket_id/documents/:document_id/pages' => "documents#view_document_pages",:as=>"view_document_pages"
  match ':docket_id/documents/:document_id/page/:page_id/customize' => 'documents#document_customize_view',:as=>"document_customize_view"
  match '/documents/structure_form/:page_id/:count' => "documents#structure_form"
  match '/docupedia' => "welcome#doclauncher"

  match 'add_new_slide' => 'slide_managements#add_new_slide'
  match 'slide' => 'slide_managements#index'
  match 'save_slide' => 'slide_managements#save_slide'
  match 'view_slide' => 'slide_managements#view_slides'

  match 'show_reference_doc/:docket_id/:document_id/:page_number'=>'test_management#show_reference_document',:as=>"show_reference_doc"

  match 'test_landing_page' => "test_management#landing_page"
  match 'play_quiz' => "test_management#play_quiz"
  match 'save_quiz_data' => "test_management#save_quiz_data"
  match '/test_manamgement/list_documents/:assignment_id/:docket_id' => "test_management#list_documents",:as=>"list_documents"
  match '/test_management/play_document_test/:docucheck_id/:sequence_number' => "test_management#play_document_test",:as=>"play_document_test"
  match 'save_document_results' => "test_management#save_document_results"
  match 'take_tutorials' => "test_management#take_tutorials"
  match "/test_management/practice/:case_study_id"=>"test_management#start_practice",:as=>"start_practice"
  match '/test_management/list_dockets/:assignment_id'=>"test_management#list_dockets",:as=>"list_dockets"

  match 'result_landing_page'=>'result_management#landing_page'
  match '/result_management/show_docket_list/:case_study_id/:assignment_id'=>'result_management#show_docket_list',:as=>"show_docket_list"
  match '/result_management/show_document_list/:case_study_id/:assignment_id/:docket_id'=>'result_management#show_document_list',:as=>"show_document_list"
  match '/result_management/show_corrected_page/:assignment_id/:docket_id/:docucheck_id/:page_id'=>'result_management#show_corrected_page',:as=>"show_corrected_page"

  match 'practice_landing_page'=>'practice_management#landing_page'
  match 'list_practice_details/:case_study_id'=>'practice_management#list_practice_details',:as=>"list_practice_details"
  match 'practice_document'=>'practice_management#practice_document'
  match 'save_practice_document_results'=>'practice_management#save_practice_document_results'

  root :to => 'welcome#index'

end

app/controllers/result_management_controller.rb
class ResultManagementController < ApplicationController

  def landing_page
    @assignments=Assignment.find_all_by_user_id(current_user.id)
    @doc_score=Array.new
    @assignments.each do |assignment|
      @doc_score[assignment.id]=0
      @docuchecks=assignment.docuchecks
      @docuchecks.each do |docu|
        @doc_score[assignment.id]=@doc_score[assignment.id]||=0+docu.score
        #   @doc_score[assignment.id]=0
      end
    end

  end

  def show_docket_list
    @case_study=CaseStudy.find(params[:case_study_id])
    @assignment=Assignment.find(params[:assignment_id])
    @dockets=@case_study.dockets

  end

  def show_document_list
    @assignment=Assignment.find(params[:assignment_id])
    @case_study=CaseStudy.find(params[:case_study_id])
    @docket=Docket.find(params[:docket_id])
    @documents=@docket.documents
  end

  def  show_page_list
    @case_study=CaseStudy.find(params[:case_study_id])
    @docket=Docket.find(params[:docket_id])
    @document=Document.find(params[:document_id])
    @pages=@document.pages
  end
  def show_corrected_page
    @assignment=Assignment.find(params[:assignment_id])
    @case_study=CaseStudy.find(@assignment.case_study_id)
    @docket=Docket.find(params[:docket_id])
    @docucheck=Docucheck.find(params[:docucheck_id])
    @document=Document.find(@docucheck.document_id)
    @pages=@document.pages

    @page=Page.find(params[:page_id])
    @blank_sections=@page.blank_sections
    @filled_sections=Array.new
    @blank_sections.each do |blank_section|
      @filled_sections << FilledSection.find_by_blank_section_id_and_docucheck_id(blank_section.id,@docucheck.id)

    end
  end
end

app/helpers/result_management_helper.rb
module ResultManagementHelper
end

app/views/result_management/landing_page.html.erb
<h3>You have the following Assignments :</h3>

<table class="table table-bordered">
  <tr>
    <th>Case Study Name</th>
    <th>Quiz Score</th>
    <th>Docu-check Score</th>

    <th></th>


  </tr>
  <% @assignments.each_with_index.each do |assignment, index| %>

      <tr>
        <td><%= CaseStudy.find(assignment.case_study_id).name %></td>

        <td><%= (Quiz.find_by_assignment_id(assignment.id).score.to_f / Quiz.find_by_assignment_id(assignment.id).qcount)*100 %>
          %
        </td>
        <td><%= link_to "Show Dockets", show_docket_list_path(assignment.case_study_id, assignment.id) %></td>

      </tr>
  <% end %>

</table>

<%= content_for :head do %>
    <style type="text/css">
    </style>

    <script type="text/javascript">
    </script>

    <style type="text/css">
    </style>

<% end %>


<div class="row-fluid">
  <div class="span3">
    <br/>
    <br/>

    <%= link_to edit_user_registration_path(current_user), :class => "btn btn-large btn-inverse", :style => "text-align: center" do %>
        <%= image_tag("users.png", :size => "64x64") %>
        <br/>
        Profile
    <% end %>
    <%= link_to result_landing_page_path, :class => "btn btn-large btn-inverse", :style => "text-align: center" do %>
        <%= image_tag("results.png", :size => "64x64") %>
        <br/>
        Results
    <% end %>
    <br/>

    <%= link_to practice_landing_page_path, :class => "btn btn-large btn-inverse", :style => "text-align: center" do %>
        <%= image_tag("practice.png", :size => "64x64") %>
        <br/>
        Practice
    <% end %>
    <%= link_to test_landing_page_path, :class => "btn btn-large btn-inverse", :style => "text-align: center" do %>
        <%= image_tag("tests.png", :size => "64x64") %>
        <br/>
        Tests
    <% end %>
    <br/>
    <br/>
    <br/>
  </div>
  <div class="span9">
    <h1>Welcome to DocuMentor</h1>
    <br/>

  </div>
</div>

app/views/result_management/show_corrected_page.html.erb
<%= content_for :nav_bar do %>
    <span style="position:absolute;  top: 8px;font-size: 17px"> :<%= link_to @document.name+": ", show_document_list_path(@case_study.id,@assignment.id, @docket.id) %>

      <% @pages.each_with_index.each do |page, index| %>

        <%= link_to "|  "+page.name, show_corrected_page_path(@assignment.id, @docket.id, @docucheck.id, page.id) %>

  <% end %>



     </span>
<% end %>


<%= content_for :head do %>


    <style type="text/css">
        .content {
            background: transparent;
        }

        .page-header {
            background: transparent;
            position: fixed;
            left: 25px;
            border: none;
            height: 600px;
            width: 220px;
            overflow: auto;
        }

        .docuframe {
            width: 900px;
            height: 1080px;
            margin: 0px auto;
            padding: 0px;
            background-image: url("<%= @page.blank_form.url(:medium) %>");
            background-repeat: no-repeat;
        }

        .component_icon {
            cursor: pointer;
        }

        .selected_icon {
            margin-left: 30px;
        }

        .selectiondiv {
            position: absolute;
            zIndex: 5000;
            border: 1px solid black
        }
    </style>

<% end %>



<div class="page-header" style="position:fixed; color:white;font-weight: bold;margin-top: 20px">



  <br/>
</div>

<div class="row" style="text-align: center; background: transparent">
  <div id="DocumentFrame" class="docuframe">
  </div>


  <% @filled_sections.each do |filled_section| %>
      <% blank_section=BlankSection.find(filled_section.blank_section_id) %>
      <% @example= Example.find(filled_section.example_id) %>

      <% if filled_section.has_no_error!=filled_section.answer_marked%>
          <%= image_tag("cross-button.png", :style => "
      position :absolute;
           z-index:6000;
           top :#{blank_section.ypos }px;
      left: #{ blank_section.xpos }px;
      background:transparent
      ", :class => filled_section.id, :size => "32x32") %>
      <% end %>


      <% if @example.is_image? %>
          <%= image_tag Example.find(filled_section.example_id).example_image.url, :id => filled_section.id, :class => "#{@class} btn option_image", :style => "
          position :absolute;
          z-index:5000;
          top :#{blank_section.ypos  }px;
          left: #{blank_section.xpos}px;
          width: #{blank_section.width+100} px;
          height:#{blank_section.height }px;
          background:transparent ;
          border:none
          ", :size => "#{blank_section.width}x#{blank_section.height}"
          %>
      <% else %>
          <p class=" btn option_image" id="<%= filled_section.id %>"
             style="     position :absolute;
                     z-index:5000;
                     top :<%= blank_section.ypos   %>px;
                     left: <%=  blank_section.xpos %>px;
                     width: <%= blank_section.width %>px;
                     height:<%= blank_section.height %>px;
                     background:transparent ;
                     border:none
             "
          >  <%= @example.text_content %></p>
      <% end %>
  <% end %>
</div>

app/views/result_management/show_docket_list.html.erb
<h3>Dockets : <%= link_to @case_study.name, result_landing_page_path %></h3>

<table class="table table-bordered">
  <tr>
    <th>Dockets Name</th>
    <th>Documents</th>

    <th></th>


  </tr>
  <% @dockets.each_with_index.each do |docket, index| %>

      <tr>
        <td><%= docket.name %></td>
        <td><%= link_to "Show Documents", show_document_list_path(@case_study.id,@assignment.id, docket.id) %></td>

      </tr>
  <% end %>

</table>

app/views/result_management/show_document_list.html.erb
<h3>Documents : <%= link_to @docket.name, show_docket_list_path(@case_study.id) %></h3>

<table class="table table-bordered">
  <tr>
    <th>Document Name</th>
    <th>Total Sections </th>
    <th>Number Of Sections Correct </th>
    <th>Number Of Sections In-Correct </th>
    <th>Document Score</th>
    <th>Pages</th>

    <th></th>


  </tr>
  <% @documents.each_with_index.each do |document, index| %>
       <% if !DocketsDocument.find_by_docket_id_and_document_id(@docket.id,document.id).reference_document?%>
      <tr>

        <td><%= document.name %></td>
        <% count=0 %>
        <% document.pages.each do |page| %>
            <% count=count+page.blank_sections.count %>
        <% end %>

        <td><%= count %></td>
        <td><%= Docucheck.find_by_document_id_and_assignment_id(document.id,@assignment.id).score %></td>
        <td><%= count- Docucheck.find_by_document_id_and_assignment_id(document.id,@assignment.id).score %></td>


        <td><%= sprintf'%.2f', (Docucheck.find_by_document_id_and_assignment_id(document.id,@assignment.id).score/count.to_f)*100 %>%</td>
        <td><%= link_to "Show Pages", show_corrected_page_path(@assignment.id, @docket.id, Docucheck.find_by_document_id_and_assignment_id(document.id,@assignment.id).id, document.pages.first.id) %></td>

      </tr>
  <% end %>
  <% end %>

</table>

app/views/result_management/show_page_list.html.erb
<%= content_for :nav_bar do %>
    <span style="position:absolute;  top: 8px;font-size: 17px"> :<%= link_to @document.name+" || ", show_document_list_path(@case_study.id, @docket.id) %>

      <% @pages.each_with_index.each do |page, index| %>

        <%= link_to page.name.gsub(".jpg", " | "), show_corrected_page_path(@case_study.id, @docket.id, @document.id, page.id) %>

  <% end %>



     </span>
<% end %>

<h3>Pages :</h3>

<table class="table table-bordered">
  <tr>
    <th>Page Name</th>
    <th>Link</th>

    <th></th>


  </tr>
  <% @pages.each_with_index.each do |page, index| %>

      <tr>
        <td><%= page.name %></td>
        <td><%= link_to "Show Corrected Page", show_corrected_page_path(@case_study.id, @docket.id, @document.id, page.id) %></td>

      </tr>
  <% end %>

</table>

app/views/result_management/view_assignment_result.html.erb
<h3>You have the following Assignments :</h3>

<table class="table table-bordered">
  <tr>
    <th>Quiz</th>
    <th>Result</th>
    <th></th>


  </tr>

      <tr>
        <td>Quiz</td>
        <td><%= Quiz.find_by_assignment_id(@assignment.id).score%></td>
        <td><%= link_to "View Results",view_assignment_result_path(:assignment_id=>@assignment.id) %></td>

      </tr>

</table>